using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ArchPillar.Extensions.Mapper.Generators;

/// <summary>
/// Emits the generated partial class source code for an AOT-compatible
/// MapperContext subclass.
/// </summary>
internal static class Emitter
{
    internal static string GenerateSource(MapperContextInfo info)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (info.Namespace != null)
        {
            sb.Append("namespace ").Append(info.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        var accessibility = AccessibilityToString(info.Accessibility);
        sb.Append(accessibility).Append(" partial class ").AppendLine(info.ClassName);
        sb.AppendLine("{");

        EmitOnAotInitialize(sb, info);
        sb.AppendLine();

        foreach (var mapper in info.Mappers)
        {
            EmitMapMethod(sb, mapper, info);
            sb.AppendLine();
            EmitMapToMethod(sb, mapper, info);
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOnAotInitialize(StringBuilder sb, MapperContextInfo info)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Wires AOT-generated mapping delegates into mapper instances,");
        sb.AppendLine("    /// eliminating the need for <c>Expression.Compile()</c> at runtime.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected override void OnAotInitialize()");
        sb.AppendLine("    {");

        foreach (var mapper in info.Mappers)
        {
            sb.Append("        ").Append(mapper.PropertyName).AppendLine(".SetCompiledDelegates(");
            sb.Append("            AotMap_").Append(mapper.PropertyName).AppendLine(",");
            sb.Append("            AotMapTo_").Append(mapper.PropertyName).AppendLine(");");
        }

        sb.AppendLine("    }");
    }

    private static void EmitMapMethod(StringBuilder sb, MapperInfo mapper, MapperContextInfo info)
    {
        var src = mapper.SourceParameterName ?? "src";
        sb.Append("    private ").Append(mapper.DestType).Append("? AotMap_").Append(mapper.PropertyName).AppendLine("(");
        sb.Append("        ").Append(mapper.SourceType).Append("? ").Append(src).AppendLine(",");
        sb.AppendLine("        global::System.Collections.Generic.List<(object, object?)>? vars)");
        sb.AppendLine("    {");
        sb.Append("        if (").Append(src).AppendLine(" is null) return default;");
        sb.AppendLine();
        sb.Append("        return new ").AppendLine(mapper.DestType);
        sb.AppendLine("        {");

        foreach (var mapping in mapper.Mappings)
        {
            if (mapping.Kind == MappingKind.Ignored || mapping.SourceExpression == null)
                continue;

            var sourceExpr = ResolveSourceExpression(mapping, src);
            var expr = ExpressionTransformer.Transform(sourceExpr, src, info);
            sb.Append("            ").Append(mapping.DestinationProperty).Append(" = ").Append(expr).AppendLine(",");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitMapToMethod(StringBuilder sb, MapperInfo mapper, MapperContextInfo info)
    {
        var src = mapper.SourceParameterName ?? "src";
        sb.Append("    private void AotMapTo_").Append(mapper.PropertyName).AppendLine("(");
        sb.Append("        ").Append(mapper.SourceType).Append(" ").Append(src).AppendLine(",");
        sb.Append("        ").Append(mapper.DestType).AppendLine(" dest,");
        sb.AppendLine("        global::System.Collections.Generic.List<(object, object?)>? vars)");
        sb.AppendLine("    {");

        foreach (var mapping in mapper.Mappings)
        {
            if (mapping.Kind == MappingKind.Ignored || mapping.SourceExpression == null)
                continue;

            var sourceExpr = ResolveSourceExpression(mapping, src);
            var expr = ExpressionTransformer.Transform(sourceExpr, src, info);
            sb.Append("        dest.").Append(mapping.DestinationProperty).Append(" = ").Append(expr).AppendLine(";");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// If a fluent mapping used a different lambda parameter name than the main
    /// CreateMapper lambda, rename it to match the generated method parameter.
    /// </summary>
    private static string ResolveSourceExpression(PropertyMappingInfo mapping, string targetParam)
    {
        var expr = mapping.SourceExpression!;

        if (mapping.LambdaParameterName != null && mapping.LambdaParameterName != targetParam)
        {
            // Replace "x." with "src." at the start and after non-identifier chars
            expr = ReplaceParameterName(expr, mapping.LambdaParameterName, targetParam);
        }

        return expr;
    }

    private static string ReplaceParameterName(string expr, string oldName, string newName)
    {
        var result = new StringBuilder(expr.Length + 16);
        var i = 0;
        while (i < expr.Length)
        {
            var idx = expr.IndexOf(oldName, i, StringComparison.Ordinal);
            if (idx < 0)
            {
                result.Append(expr.Substring(i));
                break;
            }

            // Check boundaries
            var beforeOk = idx == 0 || !IsIdentifierChar(expr[idx - 1]);
            var afterOk = idx + oldName.Length >= expr.Length
                || !IsIdentifierChar(expr[idx + oldName.Length]);

            if (beforeOk && afterOk)
            {
                result.Append(expr.Substring(i, idx - i));
                result.Append(newName);
                i = idx + oldName.Length;
            }
            else
            {
                result.Append(expr.Substring(i, idx + oldName.Length - i));
                i = idx + oldName.Length;
            }
        }

        return result.ToString();
    }

    private static bool IsIdentifierChar(char c)
    {
        return (c >= 'a' && c <= 'z')
            || (c >= 'A' && c <= 'Z')
            || (c >= '0' && c <= '9')
            || c == '_';
    }

    private static string AccessibilityToString(Accessibility a)
    {
        switch (a)
        {
            case Accessibility.Public: return "public";
            case Accessibility.Internal: return "internal";
            case Accessibility.Protected: return "protected";
            case Accessibility.ProtectedOrInternal: return "protected internal";
            case Accessibility.ProtectedAndInternal: return "private protected";
            case Accessibility.Private: return "private";
            default: return "public";
        }
    }
}
