using System.Collections.Immutable;
using System.Text;
using ArchPillar.Extensions.Localization.Detection;
using ArchPillar.Extensions.Localization.Generator.Internal;

namespace ArchPillar.Extensions.Localization.Generator;

/// <summary>
/// Emits the strongly-typed key registry (<c>const</c> per discovered key) so call sites and the
/// analyzer get autocomplete and rename-safe keys.
/// </summary>
internal static class TranslationKeyRegistryEmitter
{
    public static string Emit(ImmutableArray<TranslationSite?> sites)
    {
        SortedDictionary<string, SortedSet<string>> byCategory = GroupByCategory(sites);

        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n");
        builder.Append("namespace ArchPillar.Extensions.Localization;\n\n");
        builder.Append("/// <summary>Strongly-typed translation keys discovered at compile time, grouped by category.</summary>\n");
        builder.Append("internal static class TranslationKeys\n{\n");

        // Global (uncategorized) keys sit at the top level; each category becomes a nested class, so the
        // same key under two categories produces two distinct constants instead of colliding.
        if (byCategory.TryGetValue(string.Empty, out SortedSet<string>? globalKeys))
        {
            AppendConstants(builder, globalKeys, "    ");
        }

        var usedClasses = new HashSet<string>(StringComparer.Ordinal);
        foreach (KeyValuePair<string, SortedSet<string>> category in byCategory)
        {
            if (category.Key.Length == 0)
            {
                continue;
            }

            var className = Unique(KeyIdentifier.ToIdentifier(category.Key), usedClasses);
            builder.Append("\n    /// <summary>Keys for category <c>").Append(Escape(category.Key)).Append("</c>.</summary>\n");
            builder.Append("    public static class ").Append(className).Append("\n    {\n");
            AppendConstants(builder, category.Value, "        ");
            builder.Append("    }\n");
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    private static void AppendConstants(StringBuilder builder, SortedSet<string> keys, string indent)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var key in keys)
        {
            var identifier = Unique(KeyIdentifier.ToIdentifier(key), used);
            builder.Append(indent).Append("public const string ").Append(identifier).Append(" = \"").Append(Escape(key)).Append("\";\n");
        }
    }

    private static SortedDictionary<string, SortedSet<string>> GroupByCategory(ImmutableArray<TranslationSite?> sites)
    {
        var byCategory = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        foreach (TranslationSite? site in sites)
        {
            if (site is null)
            {
                continue;
            }

            if (!byCategory.TryGetValue(site.Category, out SortedSet<string>? keys))
            {
                keys = new SortedSet<string>(StringComparer.Ordinal);
                byCategory[site.Category] = keys;
            }

            keys.Add(site.Key);
        }

        return byCategory;
    }

    private static string Unique(string identifier, HashSet<string> used)
    {
        var candidate = identifier;
        var suffix = 2;
        while (!used.Add(candidate))
        {
            candidate = identifier + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");
}
