using System.Collections.Immutable;
using System.Text;
using ArchPillar.Extensions.Localization.Detection;
using ArchPillar.Extensions.Localization.Generator.Internal;

namespace ArchPillar.Extensions.Localization.Generator;

/// <summary>
/// Emits the strongly-typed key registry (<c>const</c> per discovered key) so call sites and the
/// analyzer get autocomplete and rename-safe keys.
/// </summary>
internal static class TranslationKeyRegistryEmitter
{
    public static string Emit(ImmutableArray<TranslationSite?> sites)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n");
        builder.Append("namespace ArchPillar.Extensions.Localization;\n\n");
        builder.Append("/// <summary>Strongly-typed translation keys discovered at compile time.</summary>\n");
        builder.Append("internal static class TranslationKeys\n{\n");
        foreach ((var identifier, var key) in CollectKeys(sites))
        {
            builder.Append("    public const string ").Append(identifier).Append(" = \"").Append(Escape(key)).Append("\";\n");
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    private static List<(string Identifier, string Key)> CollectKeys(ImmutableArray<TranslationSite?> sites)
    {
        var distinct = new SortedSet<string>(StringComparer.Ordinal);
        foreach (TranslationSite? site in sites)
        {
            if (site is not null)
            {
                distinct.Add(site.Key);
            }
        }

        var used = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<(string Identifier, string Key)>();
        foreach (var key in distinct)
        {
            result.Add((Unique(KeyIdentifier.ToIdentifier(key), used), key));
        }

        return result;
    }

    private static string Unique(string identifier, HashSet<string> used)
    {
        var candidate = identifier;
        var suffix = 2;
        while (!used.Add(candidate))
        {
            candidate = identifier + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");
}
