<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Localization\ArchPillar.Extensions.Localization.csproj" />
    <ProjectReference Include="..\..\src\Localization.Tooling\ArchPillar.Extensions.Localization.Tooling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
