#!/usr/bin/env python3
"""Generate CldrPluralData.g.cs from the pinned CLDR plural-rule data.

Source data: eng/cldr/plurals.json and eng/cldr/ordinals.json
(from unicode-org/cldr-json, cldr-core/supplemental).

Regenerate after bumping the pinned data:
    python3 eng/cldr/generate_plural_data.py
"""
import json
import os

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "..", "..", "src", "Localization.MessageFormat",
                   "Internal", "CldrPluralData.g.cs")

CATS = {"zero": "Zero", "one": "One", "two": "Two",
        "few": "Few", "many": "Many", "other": "Other"}


def load(filename, key):
    data = json.load(open(os.path.join(HERE, filename)))["supplemental"]
    table = {}
    for lang, rules in data[key].items():
        items = []
        for rule_key, value in rules.items():
            category = rule_key.split("-")[-1]
            condition = value.split("@")[0].strip()
            if category == "other" or condition == "":
                continue
            items.append((CATS[category], condition))
        if items:
            table[lang.replace("_", "-").lower()] = items
    return table


def emit(table):
    lines = []
    for lang in sorted(table):
        parts = ", ".join(
            f'new(PluralCategory.{cat}, "{cond}")' for cat, cond in table[lang])
        lines.append(f'        ["{lang}"] = new CldrPluralRule[] {{ {parts} }},')
    return "\n".join(lines)


cardinal = load("plurals.json", "plurals-type-cardinal")
ordinal = load("ordinals.json", "plurals-type-ordinal")
version = json.load(open(os.path.join(HERE, "plurals.json")))[
    "supplemental"]["version"]["_cldrVersion"]

content = f"""// <auto-generated/>
#nullable enable
namespace ArchPillar.Extensions.Localization.MessageFormat.Internal;

/// <summary>
/// CLDR plural-rule conditions, generated from the pinned data in <c>eng/cldr</c>.
/// Do not edit by hand; run <c>eng/cldr/generate_plural_data.py</c> to regenerate.
/// </summary>
internal static class CldrPluralData
{{
    public const string CldrVersion = "{version}";

    public static System.Collections.Generic.IReadOnlyDictionary<string, CldrPluralRule[]> Cardinal {{ get; }} =
        new System.Collections.Generic.Dictionary<string, CldrPluralRule[]>(System.StringComparer.OrdinalIgnoreCase)
    {{
{emit(cardinal)}
    }};

    public static System.Collections.Generic.IReadOnlyDictionary<string, CldrPluralRule[]> Ordinal {{ get; }} =
        new System.Collections.Generic.Dictionary<string, CldrPluralRule[]>(System.StringComparer.OrdinalIgnoreCase)
    {{
{emit(ordinal)}
    }};
}}
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf-8").write(content)
print(f"cardinal={len(cardinal)} ordinal={len(ordinal)} cldr={version}")
