// eng/cldr/numbers.json -> src/Localization.MessageFormat/Internal/CldrNumberPatterns.g.cs.
//
// .NET 10 file-based app — regenerate after bumping the pinned data:
//     dotnet run eng/cldr/generate-number-patterns.cs
using System.Text;
using System.Text.Json.Nodes;

var here = ScriptDirectory();
JsonNode data = JsonNode.Parse(File.ReadAllText(Path.Combine(here, "numbers.json")))!;
var version = (string)data["version"]!["_cldrVersion"]!;
JsonObject locales = data["locales"]!.AsObject();

// Dedupe identical pattern triples into shared instances. '|' never occurs in CLDR number patterns,
// so it is a safe join separator (guarded below anyway).
var sets = new SortedDictionary<string, List<string>>(StringComparer.Ordinal);
foreach ((var locale, JsonNode? entry) in locales)
{
    var triple = new[] { (string)entry!["decimal"]!, (string)entry["percent"]!, (string)entry["currency"]! };
    if (triple.Any(pattern => pattern.Contains('|')))
    {
        throw new InvalidOperationException($"Locale '{locale}' has a pattern containing '|'; pick a new separator.");
    }

    var key = string.Join("|", triple);
    if (!sets.TryGetValue(key, out List<string>? members))
    {
        members = new List<string>();
        sets[key] = members;
    }

    members.Add(locale);
}

var fields = new StringBuilder();
var entries = new List<string>();
var index = 0;
foreach ((var key, List<string> members) in sets)
{
    var parts = key.Split('|');
    fields.Append($"    private static readonly CldrNumberPatternSet _set{index} = new(\"{Cs(parts[0])}\", \"{Cs(parts[1])}\", \"{Cs(parts[2])}\");").Append('\n');
    foreach (var locale in members)
    {
        entries.Add($"        [\"{locale}\"] = _set{index},");
    }

    index++;
}

entries.Sort(StringComparer.Ordinal);

var content = $$"""
// <auto-generated/>
#nullable enable
namespace ArchPillar.Extensions.Localization.MessageFormat.Internal;

/// <summary>
/// CLDR standard number patterns (decimal/percent/currency), generated from the pinned data in
/// <c>eng/cldr</c>. Do not edit by hand; run <c>dotnet run eng/cldr/generate-number-patterns.cs</c> to regenerate.
/// </summary>
internal static class CldrNumberPatterns
{
    public const string CldrVersion = "{{version}}";

{{fields.ToString().TrimEnd()}}

    public static System.Collections.Generic.IReadOnlyDictionary<string, CldrNumberPatternSet> Locales { get; } =
        new System.Collections.Generic.Dictionary<string, CldrNumberPatternSet>(System.StringComparer.OrdinalIgnoreCase)
    {
{{string.Join("\n", entries)}}
    };
}
""";

var outPath = Path.Combine(here, "..", "..", "src", "Localization.MessageFormat", "Internal", "CldrNumberPatterns.g.cs");
File.WriteAllText(outPath, content + "\n");
Console.WriteLine($"locales={locales.Count} sets={sets.Count} cldr={version} -> {Path.GetFullPath(outPath)}");

static string Cs(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

static string ScriptDirectory([System.Runtime.CompilerServices.CallerFilePath] string path = "") =>
    Path.GetDirectoryName(path)!;
