// eng/cldr/compact.json -> src/Localization.MessageFormat/Internal/CldrCompactData.g.cs.
//
// .NET 10 file-based app — regenerate after bumping the pinned data:
//     dotnet run eng/cldr/generate-compact-data.cs
using System.Text;
using System.Text.Json.Nodes;

var here = ScriptDirectory();
JsonNode data = JsonNode.Parse(File.ReadAllText(Path.Combine(here, "compact.json")))!;
var version = (string)data["version"]!["_cldrVersion"]!;
JsonObject locales = data["locales"]!.AsObject();

// Build one C# expression per locale (a `new CompactLocaleData(...)`), dedupe identical expressions into
// shared fields, and emit the locale->field map. Ordinal-stable ordering keeps the generated file diff-clean.
var expressions = new SortedDictionary<string, string>(StringComparer.Ordinal);
foreach (var (locale, entry) in locales)
{
    expressions[locale] = LocaleExpression(entry!.AsObject());
}

var sets = new SortedDictionary<string, List<string>>(StringComparer.Ordinal);
foreach (var (locale, expression) in expressions)
{
    if (!sets.TryGetValue(expression, out var members))
    {
        members = new List<string>();
        sets[expression] = members;
    }

    members.Add(locale);
}

var fields = new StringBuilder();
var mapEntries = new List<string>();
var index = 0;
foreach (var (expression, members) in sets)
{
    fields.Append($"    private static readonly CompactLocaleData _data{index} = {expression};").Append('\n');
    foreach (var locale in members)
    {
        mapEntries.Add($"        [\"{locale}\"] = _data{index},");
    }

    index++;
}

mapEntries.Sort(StringComparer.Ordinal);

var content = $$"""
// <auto-generated/>
#nullable enable
namespace ArchPillar.Extensions.Localization.MessageFormat.Internal;

/// <summary>
/// CLDR compact number patterns (short/long decimal and short currency), generated from the pinned data in
/// <c>eng/cldr</c>. Do not edit by hand; run <c>dotnet run eng/cldr/generate-compact-data.cs</c> to regenerate.
/// </summary>
internal static class CldrCompactData
{
    public const string CldrVersion = "{{version}}";

{{fields.ToString().TrimEnd()}}

    public static System.Collections.Generic.IReadOnlyDictionary<string, CompactLocaleData> Locales { get; } =
        new System.Collections.Generic.Dictionary<string, CompactLocaleData>(System.StringComparer.OrdinalIgnoreCase)
    {
{{string.Join("\n", mapEntries)}}
    };
}
""";

var outPath = Path.Combine(here, "..", "..", "src", "Localization.MessageFormat", "Internal", "CldrCompactData.g.cs");
File.WriteAllText(outPath, content + "\n");
Console.WriteLine($"locales={locales.Count} sets={sets.Count} cldr={version} -> {Path.GetFullPath(outPath)}");

static string LocaleExpression(JsonObject entry) =>
    $"new CompactLocaleData({SetExpression(entry, "shortDecimal")}, {SetExpression(entry, "longDecimal")}, "
    + $"{SetExpression(entry, "shortCurrency")}, {SetExpression(entry, "shortCurrencyAlpha")})";

static string SetExpression(JsonObject entry, string name)
{
    if (entry[name] is not JsonObject magnitudes)
    {
        return "null";
    }

    var buckets = new List<string>();
    foreach (var (magnitude, counts) in magnitudes)
    {
        var variants = new List<string>();
        foreach (var (count, pattern) in counts!.AsObject())
        {
            // A numeric count (e.g. "1") is a CLDR explicit value; a keyword ("one"/"other"/…) is a plural category.
            var isExplicit = count.Length > 0 && count.All(char.IsDigit);
            var explicitValue = isExplicit ? $"{count}m" : "null";
            var category = isExplicit ? "Other" : Category(count);
            variants.Add($"new(PluralCategory.{category}, {explicitValue}, \"{Cs((string)pattern!)}\")");
        }

        buckets.Add($"new({magnitude}m, new CompactVariant[] {{ {string.Join(", ", variants)} }})");
    }

    return $"new CompactBucketSet(new CompactBucket[] {{ {string.Join(", ", buckets)} }})";
}

static string Category(string count) => count switch
{
    "zero" => "Zero",
    "one" => "One",
    "two" => "Two",
    "few" => "Few",
    "many" => "Many",
    "other" => "Other",
    _ => throw new InvalidOperationException($"Unknown plural count '{count}'.")
};

static string Cs(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

static string ScriptDirectory([System.Runtime.CompilerServices.CallerFilePath] string path = "") =>
    Path.GetDirectoryName(path)!;
