// eng/cldr/currencies.json + currency-fractions.json -> src/.../Internal/CldrCurrencyData.{bin,g.cs}.
//
// Delta-encodes the pinned CLDR currency-display data (per-locale symbol/narrow/plural-names, unitPattern,
// currencySpacing) plus the minor-unit fraction overrides into the LF/TAB text stream described by the
// "Shared Data-Format Contract" in the Spec 5 plan, Deflate-compresses it into the committed
// CldrCurrencyData.bin embedded resource, and writes the tiny CldrCurrencyData.g.cs pin. Only entries that
// differ from their resolved locale->language->root parent are emitted (root emits all it has), which keeps
// the compressed resource well under 1 MB. The per-entry work lives in the CldrTooling.CurrencyGen helper (a
// named namespace keeps the top-level orchestrator thin and each step individually maintainable — CA1505).
// .NET 10 file-based app — regenerate after bumping the pinned data:
//     dotnet run eng/cldr/generate-currency-data.cs
using System.IO.Compression;
using System.Text;
using System.Text.Json.Nodes;
using CldrTooling;

var here = CurrencyGen.ScriptDirectory();
JsonObject currencies = JsonNode.Parse(File.ReadAllText(Path.Combine(here, "currencies.json")))!["locales"]!.AsObject();
JsonNode fractionsDoc = JsonNode.Parse(File.ReadAllText(Path.Combine(here, "currency-fractions.json")))!;
var version = (string)fractionsDoc["version"]!["_cldrVersion"]!;

List<string> lines = CurrencyGen.Build(currencies, fractionsDoc, version);
var payload = Encoding.UTF8.GetBytes(string.Join("\n", lines) + "\n");
var internalDir = Path.Combine(here, "..", "..", "src", "Localization.MessageFormat", "Internal");
var binPath = Path.Combine(internalDir, "CldrCurrencyData.bin");
CurrencyGen.WriteResource(binPath, payload);
CurrencyGen.WriteMetadata(Path.Combine(internalDir, "CldrCurrencyData.g.cs"), version);

Console.WriteLine($"lines={lines.Count} bin={new FileInfo(binPath).Length / 1024} KiB cldr={version}");

namespace CldrTooling
{
    internal static class CurrencyGen
    {
        private const char Us = '\u001F';

        // currencies.json + currency-fractions.json -> the ordered record lines (V, R*, K*, P*, L*, C*).
        public static List<string> Build(JsonObject currencies, JsonNode fractionsDoc, string version)
        {
            var localeCodes = new Dictionary<string, Dictionary<string, (string Sym, string Narrow, string Names)>>(StringComparer.Ordinal);
            var localeMeta = new Dictionary<string, (string Pattern, string Spacing)>(StringComparer.Ordinal);
            BuildModel(currencies, localeCodes, localeMeta);

            var lines = new List<string> { $"V\t{version}" };
            foreach ((var code, JsonNode? d) in fractionsDoc["digits"]!.AsObject())
            {
                lines.Add($"R\t{code}\t{(int)d!}");
            }

            // Intern the spacing + unitPattern sets while emitting the per-locale meta lines, then flush the
            // deduped pools (index order) ahead of the L lines that reference them.
            var spacingIndex = new Dictionary<string, int>(StringComparer.Ordinal);
            var patternIndex = new Dictionary<string, int>(StringComparer.Ordinal);
            var localeLines = new List<string>();
            foreach ((var locale, (var pattern, var spacing)) in localeMeta.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                localeLines.Add($"L\t{locale}\t{Intern(patternIndex, pattern)}\t{Intern(spacingIndex, spacing)}");
            }

            foreach ((var value, var i) in spacingIndex.OrderBy(p => p.Value))
            {
                lines.Add($"K\t{i}\t{value}");
            }

            foreach ((var value, var i) in patternIndex.OrderBy(p => p.Value))
            {
                lines.Add($"P\t{i}\t{value}");
            }

            lines.AddRange(localeLines);
            EmitCurrencies(lines, localeCodes);
            return lines;
        }

        public static void WriteResource(string path, byte[] payload)
        {
            using FileStream file = File.Create(path);
            using var deflate = new DeflateStream(file, CompressionLevel.SmallestSize);
            deflate.Write(payload, 0, payload.Length);
        }

        public static void WriteMetadata(string path, string version) =>
            File.WriteAllText(path, $$"""
// <auto-generated/>
#nullable enable
namespace ArchPillar.Extensions.Localization.MessageFormat.Internal;

/// <summary>
/// Pin metadata for the compressed CLDR currency-display resource (<c>CldrCurrencyData.bin</c>), generated
/// from the pinned data in <c>eng/cldr</c>. Do not edit by hand; run
/// <c>dotnet run eng/cldr/generate-currency-data.cs</c> to regenerate.
/// </summary>
internal static class CldrCurrencyData
{
    public const string CldrVersion = "{{version}}";
    public const string ResourceName = "ArchPillar.Extensions.Localization.MessageFormat.Internal.CldrCurrencyData.bin";
}
""" + "\n");

        public static string ScriptDirectory([System.Runtime.CompilerServices.CallerFilePath] string path = "") =>
            Path.GetDirectoryName(path)!;

        // locale -> code -> (symbol, narrow, names) and locale -> (unitPattern set, spacing). CLDR publishes
        // root data under "und"; the resolver's fallback chain terminates at "root", so remap here.
        private static void BuildModel(
            JsonObject currencies,
            Dictionary<string, Dictionary<string, (string Sym, string Narrow, string Names)>> localeCodes,
            Dictionary<string, (string Pattern, string Spacing)> localeMeta)
        {
            foreach ((var rawLocale, JsonNode? node) in currencies)
            {
                var locale = rawLocale == "und" ? "root" : rawLocale;
                JsonObject bucket = node!.AsObject();
                var codes = new Dictionary<string, (string, string, string)>(StringComparer.Ordinal);
                if (bucket["currencies"] is JsonObject cur)
                {
                    foreach ((var code, JsonNode? c) in cur)
                    {
                        JsonObject o = c!.AsObject();
                        var sym = (string?)o["symbol"] ?? code;
                        var narrow = (string?)o["narrow"] ?? "";
                        var names = o["names"] is JsonObject nm
                            ? string.Join(Us, nm.Select(p => $"{p.Key}={(string)p.Value!}"))
                            : "";
                        codes[code] = (sym, narrow == sym ? "" : narrow, names);
                    }
                }

                localeCodes[locale] = codes;
                var patterns = bucket["unitPattern"] is JsonObject up
                    ? string.Join(Us, up.Select(p => $"{p.Key}={(string)p.Value!}"))
                    : "other={0} {1}";
                localeMeta[locale] = (patterns, (string?)bucket["spacing"] ?? "\u00A0");
            }
        }

        // Emit a C line only when the entry differs from its resolved parent (delta); root emits all it has.
        private static void EmitCurrencies(
            List<string> lines,
            Dictionary<string, Dictionary<string, (string Sym, string Narrow, string Names)>> localeCodes)
        {
            foreach ((var locale, Dictionary<string, (string Sym, string Narrow, string Names)> codes) in localeCodes.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                foreach ((var code, (var sym, var narrow, var names)) in codes.OrderBy(p => p.Key, StringComparer.Ordinal))
                {
                    (string Sym, string Narrow, string Names)? parent = locale == "root" ? null : Resolve(localeCodes, Parent(locale), code);
                    if (parent is { } p && p.Sym == sym && p.Narrow == narrow && p.Names == names)
                    {
                        continue;
                    }

                    lines.Add($"C\t{locale}\t{code}\t{sym}\t{narrow}\t{names}");
                }
            }
        }

        private static string Parent(string locale)
        {
            var dash = locale.IndexOf('-');
            return dash > 0 ? locale[..dash] : "root";
        }

        private static (string Sym, string Narrow, string Names)? Resolve(
            Dictionary<string, Dictionary<string, (string Sym, string Narrow, string Names)>> localeCodes,
            string locale,
            string code)
        {
            var l = locale;
            while (true)
            {
                if (localeCodes.TryGetValue(l, out Dictionary<string, (string Sym, string Narrow, string Names)>? m)
                    && m.TryGetValue(code, out (string Sym, string Narrow, string Names) e))
                {
                    return e;
                }

                if (l == "root")
                {
                    return null;
                }

                l = Parent(l);
            }
        }

        private static int Intern(Dictionary<string, int> pool, string value)
        {
            if (!pool.TryGetValue(value, out var i))
            {
                i = pool.Count;
                pool[value] = i;
            }

            return i;
        }
    }
}
