// <auto-generated/>
#nullable enable
namespace ArchPillar.Extensions.Localization.MessageFormat.Internal;

/// <summary>
/// Pin metadata for the compressed CLDR currency-display resource (<c>CldrCurrencyData.bin</c>), generated
/// from the pinned data in <c>eng/cldr</c>. Do not edit by hand; run
/// <c>dotnet run eng/cldr/generate-currency-data.cs</c> to regenerate.
/// </summary>
internal static class CldrCurrencyData
{
    public const string CldrVersion = "48";
    public const string ResourceName = "ArchPillar.Extensions.Localization.MessageFormat.Internal.CldrCurrencyData.bin";
}
