using System.Collections.Immutable;
using System.Text;
using ArchPillar.Extensions.Localization.Generator.Internal;

namespace ArchPillar.Extensions.Localization.Generator;

/// <summary>
/// Emits the constructors for each <c>partial</c> <c>Localized&lt;T&gt;</c> bundle that declares none: a
/// parameterless ambient constructor and an <c>ILocalizer&lt;TSelf&gt;</c> constructor for injection, so a
/// partial bundle works with a bare <c>new</c> and through the DI registration without hand-written plumbing.
/// Returns <see langword="null"/> when no bundle needs them.
/// </summary>
internal static class LocalizedBundleConstructorEmitter
{
    public static string? Emit(ImmutableArray<LocalizedBundleEmit?> bundles)
    {
        // Group by namespace, both sorted, so the output is deterministic regardless of discovery order.
        var byNamespace = new SortedDictionary<string, SortedDictionary<string, string>>(StringComparer.Ordinal);
        foreach (var bundle in bundles)
        {
            if (bundle is not { GenerateConstructor: true })
            {
                continue;
            }

            var namespaceName = bundle.Namespace ?? string.Empty;
            if (!byNamespace.TryGetValue(namespaceName, out SortedDictionary<string, string>? types))
            {
                types = new SortedDictionary<string, string>(StringComparer.Ordinal);
                byNamespace[namespaceName] = types;
            }

            types[bundle.TypeName] = bundle.FullyQualifiedName;
        }

        if (byNamespace.Count == 0)
        {
            return null;
        }

        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n");

        foreach (KeyValuePair<string, SortedDictionary<string, string>> namespaceGroup in byNamespace)
        {
            var hasNamespace = namespaceGroup.Key.Length > 0;
            var indent = hasNamespace ? "    " : string.Empty;
            builder.Append('\n');
            if (hasNamespace)
            {
                builder.Append("namespace ").Append(namespaceGroup.Key).Append("\n{\n");
            }

            var first = true;
            foreach (KeyValuePair<string, string> type in namespaceGroup.Value)
            {
                if (!first)
                {
                    builder.Append('\n');
                }

                first = false;
                AppendConstructors(builder, indent, type.Key, type.Value);
            }

            if (hasNamespace)
            {
                builder.Append("}\n");
            }
        }

        return builder.ToString();
    }

    private static void AppendConstructors(StringBuilder builder, string indent, string typeName, string fullyQualifiedName)
    {
        builder.Append(indent).Append("partial class ").Append(typeName).Append('\n').Append(indent).Append("{\n");
        builder.Append(indent).Append("    /// <summary>Ambient construction — resolves the localizer from the process-wide ambient context.</summary>\n");
        builder.Append(indent).Append("    public ").Append(typeName).Append("()\n").Append(indent).Append("    {\n").Append(indent).Append("    }\n\n");
        builder.Append(indent).Append("    /// <summary>Dependency-injection construction — the localizer is supplied by the container.</summary>\n");
        builder.Append(indent).Append("    public ").Append(typeName).Append("(global::ArchPillar.Extensions.Localization.ILocalizer<").Append(fullyQualifiedName).Append("> localizer)\n");
        builder.Append(indent).Append("        : base(localizer)\n").Append(indent).Append("    {\n").Append(indent).Append("    }\n");
        builder.Append(indent).Append("}\n");
    }
}
