using System.Collections.Immutable;
using System.Text;
using ArchPillar.Extensions.Localization.Generator.Internal;

namespace ArchPillar.Extensions.Localization.Generator;

/// <summary>
/// Emits an <c>internal</c> <c>AddArchPillarLocalizedBundles</c> extension that registers every discovered
/// <c>Localized&lt;T&gt;</c> bundle as a singleton, resolved through its <c>ILocalizer&lt;T&gt;</c> constructor.
/// Generated only when the compilation references the dependency-injection abstractions, so an ambient-only
/// consumer is unaffected. Returns <see langword="null"/> when no injectable bundle was found.
/// </summary>
internal static class LocalizedBundleRegistrationEmitter
{
    public static string? Emit(ImmutableArray<LocalizedBundleEmit?> bundles)
    {
        var names = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var bundle in bundles)
        {
            if (bundle is { Register: true })
            {
                names.Add(bundle.FullyQualifiedName);
            }
        }

        if (names.Count == 0)
        {
            return null;
        }

        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n");
        builder.Append("namespace Microsoft.Extensions.DependencyInjection;\n\n");
        builder.Append("/// <summary>Registers the <c>Localized&lt;T&gt;</c> string bundles discovered in this assembly with the DI container.</summary>\n");
        builder.Append("internal static class ArchPillarLocalizedBundleRegistration\n{\n");
        builder.Append("    /// <summary>Registers every discovered <c>Localized&lt;T&gt;</c> bundle as a singleton, resolved through its <c>ILocalizer&lt;T&gt;</c> constructor.</summary>\n");
        builder.Append("    /// <param name=\"services\">The service collection.</param>\n");
        builder.Append("    /// <returns>The same service collection, for chaining.</returns>\n");
        builder.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddArchPillarLocalizedBundles(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)\n    {\n");

        foreach (var name in names)
        {
            builder
                .Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(services, static serviceProvider => new ")
                .Append(name)
                .Append("(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ArchPillar.Extensions.Localization.ILocalizer<")
                .Append(name)
                .Append(">>(serviceProvider)));\n");
        }

        builder.Append("        return services;\n");
        builder.Append("    }\n}\n");
        return builder.ToString();
    }
}
