using System.Collections.Immutable;
using System.Text;
using ArchPillar.Extensions.Localization.Detection;
using ArchPillar.Extensions.Localization.Generator.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace ArchPillar.Extensions.Localization.Generator;

/// <summary>
/// The compile-time extraction engine. It emits the strongly-typed key registry as source, and bakes
/// the source-language template (ARB, Base64-encoded) into the output assembly via an assembly
/// attribute. Generators may not do file I/O, so a build task or the tool materializes the template on
/// disk from that attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class TranslationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<TranslationSite?>> sites = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax or BaseObjectCreationExpressionSyntax or ElementAccessExpressionSyntax,
                static (syntaxContext, ct) =>
                    TranslationSiteDetector.DetectAt(syntaxContext.SemanticModel, syntaxContext.Node, includeStringLocalizer: true, ct)?.Site)
            .Where(static site => site is not null)
            .Collect();

        context.RegisterSourceOutput(
            sites,
            static (production, collected) =>
                production.AddSource("TranslationKeys.g.cs", TranslationKeyRegistryEmitter.Emit(collected)));

        context.RegisterSourceOutput(
            sites.Combine(context.AnalyzerConfigOptionsProvider),
            static (production, pair) => EmitTemplate(production, pair.Left, pair.Right));
    }

    private static void EmitTemplate(
        SourceProductionContext production,
        ImmutableArray<TranslationSite?> sites,
        AnalyzerConfigOptionsProvider options)
    {
        AnalyzerConfigOptions global = options.GlobalOptions;
        if (!IsEmitEnabled(global))
        {
            return;
        }

        var sourceLanguage = Property(global, "ArchPillarLocalizationSourceLanguage") ?? "en";
        var format = Property(global, "ArchPillarLocalizationFormat") ?? "arb";
        var arb = ArbTemplateWriter.Write(Collect(sites), sourceLanguage);
        var base64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(arb));
        production.AddSource("LocalizationTemplate.g.cs", BakeAttribute(format, sourceLanguage, base64));
    }

    private static string BakeAttribute(string format, string sourceLanguage, string base64) =>
        "// <auto-generated/>\n"
        + "[assembly: global::ArchPillar.Extensions.Localization.GeneratedLocalizationTemplate("
        + Literal(format) + ", " + Literal(sourceLanguage) + ", " + Literal(base64) + ")]\n";

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static List<TranslationSite> Collect(ImmutableArray<TranslationSite?> sites)
    {
        var concrete = new List<TranslationSite>();
        foreach (TranslationSite? site in sites)
        {
            if (site is not null)
            {
                concrete.Add(site);
            }
        }

        return concrete;
    }

    private static bool IsEmitEnabled(AnalyzerConfigOptions options) =>
        !string.Equals(Property(options, "ArchPillarLocalizationEmit"), "false", StringComparison.OrdinalIgnoreCase);

    private static string? Property(AnalyzerConfigOptions options, string name) =>
        options.TryGetValue("build_property." + name, out var value) ? value : null;
}
